### PR TITLE
fix eslint error and defined issue from product.service.test

### PR DESCRIPTION
**Pull request by bhsoyket**
#38 fix eslint error and defined issue.

### CODE REVIEW

**Comment by foyzulkarim** [comment]
@bhsoyket bro you targeted wrong branch. we are not ready to merge this in `main` branch

**Comment by bhsoyket** [comment]
I am really sorry bro. I change destination branch to `/chore/v50/role-crud`

**Comment by foyzulkarim** [comment]
@bhsoyket brother. please remove the `package.lock.json` file from the pull request. Thanks for your hard work :)

**Review by foyzulkarim — CHANGES_REQUESTED** [review]
please remove `package-lock.json` file 
Thanks.

**Comment by bhsoyket** [comment]
can i add the package-lock.json file to .gitignore?

**Comment by foyzulkarim** [comment]
I think we should not put it in .gitignore

**Comment by foyzulkarim** [comment]
this pull request is obsolete now. closing it. thanks for your efforts

**Pull request closed without merging**
